ALTER TABLE users ADD user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE messages ADD m_id INT NOT NULL FIRST;
ALTER TABLE messages ADD CONSTRAINT FK_users_table_user_id FOREIGN KEY (m_id)
REFERENCES users (user_id);